### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#44]
Even though the simulation has not been fully completed or QA tested, we wanted to start the code review early, so that @samreid will be able to work on it before his leave begins.  This will be the central issue for the code review, with sub-issues created and linked to this one or labeled with the "code-review" label.  Also, in order to increase the efficiency, quality and standardization of our code reviews, we have created a code-review check list, available at https://github.com/phetsims/phet-info/blob/master/code_review_checklist.md.  I'll paste it below and we can use it as a template for the review:

PhET code-review checklist
=============

**Build and Run Checks**

- [x] Does the sim pass jshint?
- [x] Does the sim build without errors?
- [x] Does the sim start up? (requirejs and built versions)
- [x] Does the sim experience any assertion failures? (run with query parameter 'ea')
- [x] Does the sim pass a scenery fuzzer test? (run with query parameter 'fuzzMouse')
- [x] Are there any strings that are not being internationalized? (run with query parameter 'stringTest=x', you should see nothing but 'x' strings)
- [x] Does the sim layout gracefully handle internationalized strings that are twice as long as the English strings? (run with query parameter 'stringTest=double') 

**Repository structure**

- [x] Are all required files and directories present?

      For a sim repository named “my-repo”, the general structure should look like this (where audio/ or images/ may be omitted if the sim doesn’t have those types of assets).

```js
   my-repo/
      assets/
         my-repo-screenshot.png
      audio/
         license.txt
      doc/
         model.md
         implementation-notes.md
      images/
         license.txt
      js/
         my-repo-config.js
         my-repo-main.js
         version.js
      strings/
         my-repo-strings_en.json
      .gitignore
      my-repo_en.html
      Gruntfile.js
      LICENSE
      package.json
      README.md
```

   For a common-code repository, the structure is similar, but some of the files and directories may not be present if the repo doesn’t have audio, images, strings, or a demo application.

- [x] Is the js/ directory properly structured? 

      All JavaScript source should be in the js/ directory. There should be a subdirectory for each screen (this also applies for single-screen sims).  For a multi-screen sim, code shared by 2 or more screens should be in a js/common/ subdirectory. Model and view code should be in model/ and view/ subdirectories for each screen and common/.  For example, for a sim with screens “Introduction” and “Custom”, the general directory structure should look like this:

```js
   my-repo/
      js/
         common/
            model/
            view/
         custom
            model/
            view/
         introduction
            model/
            view/
         my-repo-config.js
         my-repo-main.js
         version.js
 ```

- [x] Is there a file in assets/ for every file in audio/ and images/?
- [x] Are all license.txt files populated? audio/license.txt and images/license.txt should enumerate all files in those directories. For the format of license.txt files, go [here](https://github.com/phetsims/simula-rasa/blob/master/images/README.txt).
- [x] Does the README.md format and content match PhET guidelines? Was it generated by `grunt generate-published-README.md`?
- [x] Does Gruntfile.js point to `chipper/js/grunt/Gruntfile.js`?
- [x] Are dependencies in package.json the same as js/*-config.js? Do they match what is actually used by the sim? (ie, no missing dependencies, no unused dependencies)
- [x] Is the version identifier in package.json the same as js/version.js?
- [x] Is the LICENSE file correct? (Generally GPL v3 for sims, MIT for common code, but there are exceptions to this.)
- [x] Does .gitignore match other repositories?
- [x] Does *-main.js follow PhET conventions? Does it contain correct credits (options.credits passed to Sim constructor)?
- [x] Is the format of assets/*-screenshot.png correct? (2048x1344, PNG, 32-bit color) Has the browser chrome been stripped off of the screenshot?
- [x] Are there git repository branches that are no longer used and should be pruned?

**Coding conventions**

- [x] Does the code style meet PhET's code-style guidelines, as described in the [“Coding Style Guidelines” section of "PhET Development Overview"](https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit#heading=h.1oxr3ptyo50w)?
- [x] Is the code formatted according to PhET conventions? See [phet-idea-code-style.xml](https://github.com/phetsims/joist/blob/master/util/phet-idea-codestyle.xml) for IntelliJ IDEA code style.

**Documentation**

- [x] Are documentation conventions followed, as described in the [“Coding Style Guidelines” section of the PhET Development Overview](https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit#heading=h.1oxr3ptyo50w)?
- [x] Does model.md adequately describe the model, in terms appropriate for teachers?
- [x] Does implementation-notes.md adequately describe the implementation, with an overview that will be useful to future maintainers?  Issue in https://github.com/phetsims/bending-light/issues/111
- [x] Are sim-specific query parameters (if any) identified and documented in one location?

**Organization, Readability, Maintainability**

- [x] Does the organization and structure of the code make sense? Do the model and view contain types that you would expect (or guess!) by looking at the sim? Do the names of things correspond to the names that you see in the user interface?
- [x] Are appropriate design patterns used?
- [x] Is inheritance used where appropriate? Does the type hierarchy make sense?
- [x] Is there any unnecessary coupling? (e.g., by passing large objects to constructors, or exposing unnecessary properties/functions)
- [x] Are the source files reasonable in size? Scrutinize large files with too many responsibilities - can responsibilities be broken into smaller delegates?
- [x] Are any significant chunks of code duplicated?
- [x] Is there anything that should be generalized and migrated to common code?

**Performance, Usability**

- [x] Does the sim perform as desired across the range of supported platforms? (eg, not too slow on slow platforms, not too fast on fast platforms).  See https://github.com/phetsims/bending-light/issues/153
- [x] If the sim uses WebGL, does it have a fallback? Does the fallback perform reasonably well? (run with query parameter 'webgl=false').  See https://github.com/phetsims/bending-light/issues/154
- [x] Are UI components sufficiently responsive? (especially continuous UI components, such as sliders)
- [x] Are pointer areas optimized, especially for touch? (run with query parameter 'showPointerAreas')
- [x] Do pointer areas overlap? (run with query parameter 'showPointerAreas')

**Memory Leaks**

- [x] Does a heap comparison using Chrome Developer Tools indicate a memory leak? (Describing this process is beyond the scope of this document.) #155
- [x] Are there any leaks due to registration of AXON observers? 
	- [x] For each call to Property.link or PropertySet.link, is there a corresponding unlink, or documentation about why an unlink is unnecessary?
	- [x] For each DerivedProperty or Multilink created, is there a corresponding detach, or documentation about why a detach is unnecessary?
	- [x] For each common-code component (sun, scenery-phet, vegas, …) that opaquely registers an AXON observer, is there a call to that component’s dispose function, or documentation about why dispose is unnecessary?
- [x] Are there any leaks due to registration of components with TOGETHER? `together.addComponent` should be accompanied by `together.removeComponent` or documented why removeComponent is unnecessary.

**Comment by samreid** [comment]
63 files, lint free.  Builds properly, runs properly in requirejs mode and built mode.  No assertion errors noted when running under ?ea.

**Comment by samreid** [comment]
Since I am on leave, another developer such as @pixelzoom will be handling the review when it is time.

**Comment by pixelzoom** [comment]
6/18/15 dev meeting notes:

• KP: ok if we start review by 7/1/15.
• SR: There will be additional modifications done by PhET, makes sense for person doing modifications to do the review.
• CW interested in this sim for "black box" feature.
• KP: Maybe worth spending a couple of hours to add "black box" to Java version?
• SR: Recommended to put effort into HTML5 version for "black box" feature.
• AP will think about other possible sims for CW's "black box" request.
• KP: revisit this issue in 1 week.

**Comment by samreid** [comment]
6/18/15 additional dev meeting notes:

* SR suggested to work at 20% time on the code review starting right away, and AP agreed to proceed with this plan, and re-evaluate time allocations as we go.

**Comment by samreid** [comment]
I ran the sim with ?fuzzMouse for >1 minute on my OS X and didn't see any problems.

**Comment by samreid** [comment]
> Does the sim layout gracefully handle internationalized strings that are twice as long as the English strings? (run with query parameter 'stringTest=double')

I tested this and reported issues above.  I'll put a check mark but just wanted to indicate this means I've done the review, not that all work is done.

**Comment by samreid** [comment]
Fixed a naming issue above in https://github.com/phetsims/bending-light/commit/087140d7dca05137c15d6052000742a032242b5d, @ChandrashekarBemagoni can you verify that nothing was disturbed?

**Comment by samreid** [comment]
Just a note: I will be checking off items in the check list above after I have reviewed them, though issues may have been raised for them.  For instance, in:

>  Does implementation-notes.md adequately describe the implementation, with an overview that will be useful to future maintainers? Issue in #111

I checked it off and added "Issue in #111" to indicate that I have reviewed this and created an issue for it.

**Comment by samreid** [comment]
> Are the source files reasonable in size? Scrutinize large files with too many responsibilities - can responsibilities be broken into smaller delegates?

I took a snapshot of lines of code counts, everything seems distributed well.

$ find . -name '*.js' | xargs wc -l
      47 ./bending-light-config.js
      35 ./bending-light-main.js
      34 ./common/BendingLightConstants.js
     178 ./common/model/BendingLightModel.js
      94 ./common/model/DispersionFunction.js
     149 ./common/model/IntensityMeter.js
     147 ./common/model/Laser.js
     278 ./common/model/LightRay.js
      51 ./common/model/Medium.js
     101 ./common/model/MediumColorFactory.js
      42 ./common/model/MediumState.js
      50 ./common/model/ProtractorModel.js
      95 ./common/model/Reading.js
      69 ./common/model/WaveParticle.js
     186 ./common/view/BendingLightView.js
     427 ./common/view/IntensityMeterNode.js
      34 ./common/view/LaserColor.js
     194 ./common/view/LaserControlPanel.js
     160 ./common/view/LaserNode.js
      65 ./common/view/LightRayNode.js
     367 ./common/view/MediumControlPanel.js
      38 ./common/view/MediumNode.js
     323 ./common/view/ProtractorNode.js
      74 ./common/view/RotationDragHandle.js
      59 ./common/view/TranslationDragHandle.js
      78 ./common/view/WireNode.js
      33 ./intro/IntroScreen.js
     425 ./intro/model/IntroModel.js
     365 ./intro/view/IntroView.js
      40 ./intro/view/NormalLine.js
      70 ./intro/view/WaveCanvasNode.js
     212 ./intro/view/WaveWebGLNode.js
      30 ./more-tools/model/DataPoint.js
      56 ./more-tools/model/MoreToolsModel.js
      44 ./more-tools/model/Series.js
      42 ./more-tools/model/VelocitySensor.js
     157 ./more-tools/model/WaveSensor.js
      33 ./more-tools/MoreToolsScreen.js
     162 ./more-tools/view/ChartNode.js
      64 ./more-tools/view/ExpandableProtractorNode.js
      67 ./more-tools/view/GridCanvasNode.js
      70 ./more-tools/view/MoreToolsView.js
      71 ./more-tools/view/SeriesCanvasNode.js
     330 ./more-tools/view/VelocitySensorNode.js
     435 ./more-tools/view/WaveSensorNode.js
     105 ./prisms/model/Circle.js
      31 ./prisms/model/Intersection.js
     236 ./prisms/model/Polygon.js
      75 ./prisms/model/Prism.js
     405 ./prisms/model/PrismBreakModel.js
      49 ./prisms/model/Ray.js
     158 ./prisms/model/SemiCircle.js
      40 ./prisms/PrismsScreen.js
      43 ./prisms/view/IntersectionNode.js
     121 ./prisms/view/LaserTypeControlPanel.js
     144 ./prisms/view/PrismNode.js
     203 ./prisms/view/PrismsView.js
     251 ./prisms/view/PrismToolboxNode.js
     221 ./prisms/view/WhiteLightNode.js

**Comment by samreid** [comment]
> For each call to Property.link or PropertySet.link, is there a corresponding unlink, or documentation about why an unlink is unnecessary?

I think all the majority of the links/multilnks in the simulation are for the life of the sim and hence do not require unlinks.  The exception is in PrismNode, which is noted in #156.  @pixelzoom I'm not sure if it would really be best to put documentation about why unlink is necessary at all of the 43 sites in the simulation--can this somehow be "factored out" such as being placed in implementation-notes.md?

**Comment by samreid** [comment]
@kmsravindra @notsiddhartha @ChandrashekarBemagoni and @ariel-phet I have finished my initial review.  This simulation is in excellent shape and has been a job very well done so far.  @ChandrashekarBemagoni has been addressing newly created issues promptly as they are discovered.

The issues I created during the review are marked above.  Rather than marking everything with "code review" labels this time, I have just linked back issues to this issue with an issue reference.  You can scroll up through the issue to see red/green icons and the issue descriptions.

The next step is for @ChandrashekarBemagoni to finish addressing/discussing the issues I raised and for me to verify the changes.  The issue that I expect to take the longest for me to verify and has the highest potential to raise newfound issues is #141.

I'll leave this issue open until all related issues are closed.

**Comment by ChandrashekarBemagoni** [comment]
Addressed all issues related to #44. Assigning to @samreid for review

**Comment by samreid** [comment]
@ChandrashekarBemagoni your work here has been amazing, thank you for taking the time to address all of the code review issues--the code is in much better shape thanks to you.  I will also request a final QA test as part of #157 to see if anything was disturbed over the course of the changes above.  The only remaining issue assigned to you now is #147--an issue with the webgl wave view getting out of phase depending on the window size.  I'll close this review issue and we can finish up over in #147 and #157.
