### ISSUE TITLE
Bending Light Master Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/bending-light#50]
## Design
- [x] **Design doc created** (Date: 01/13/2015)
  - [x] Make phethelp@gmail.com owner, share with phet-team
  - [x] Add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
- [x] **Legacy sim docs/info gathered**
- [x] **Learning goals and standards identified** (Date: 01/16/2015)
- [x] **Design concept complete**  (Date: 01/17/2015)
- [x] **Wireframes complete** (Date: 01/17/2015) 
- [x] **Mockups complete** (Date: 01/23/2015)
  - [x] Mockups checked for colorblind and greyscale
- [x] **Design doc sent for quote** (Date: 01/19/2015)  
- [x] **Visual and interaction review of first deliverable**
- [x] **Interviews complete** (Date: 02/17/2016) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 11/19/2015) 
  - [x] Performance acceptable
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Compatible activities  
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher guide
  - [x] Update [Gooru spreadsheet](https://docs.google.com/spreadsheets/d/13qvc7e71zTTjaJ2VcYhhU0rNxvH4kYFnoScVCOvvf7U/edit#gid=1717560774)
  - [x] Sim primer (Being tracked in #366)
  - [x] Verify credits
- [x] **Add to Edmodo** 
## Implementation
- [x] **Sim repo created** (Date: 01/05/2015)
  - [x] Collaborators added (such as 3rd party, QA team, designers, etc) 
  - [x] Sim added to active repos list in chipper
  - [x] Sim suggestions doc reviewed
  - [x] Unfuddle tickets reviewed
  - [x] Existing sim tested for bugs, issues reported in repo
  - [x] Port existing strings (IF ANY) and commit to the GitHub repo
  - [x] Implementation details added to design spec
  - [x] Paste snapshot of code review checklist into repo issue
- [x] **Initial development started** (Date: 02/05/2015) 
- [x] **Sim feature complete** (Date: 05/15/2015)
- [x] **Code review complete** (Date: 11/06/2015) 
  - [x] Code review checklist
  - [x] Model description 
- [x] **PhET tweaks after sim acceptance** (Date: 12/10/2015) 
- [x] **Published** (Date: 12/23/2015) 
  - [x] Update repo README to published template
## QA
- [x] **Dev testing complete** (Date: 06/10/2015)
- [x] **First release candidate** (Date: 12/18/2015) 
- [x] **Sim accepted from third party** (Date: 10/16/2015)
- [x] **Test matrix deemed complete**

**Comment by samreid** [comment]
@arouinfar can you work on this checklist?

**Comment by ariel-phet** [comment]
@samreid I assume strings were ported over? Can you check that item if so?

**Comment by samreid** [comment]
@ariel-phet @jbphet I am out of the loop on babel.  To clarify, am I supposed to bring the non-English Java strings to babel?  Should I record which strings keys have changed from Java to HTML5 and only port strings that match the new English keys?  Is this documented somewhere?

**Comment by ariel-phet** [comment]
@pixelzoom can you answer this question, since I believe you have done this recently?

**Comment by pixelzoom** [comment]
Yes, we are still migrating strings from Java/Flash to HTML5.  But I have not done so since strings were moved to babel.   And the migration tools have not been updated to handle the migration.  The plan was that whoever needed to do a migration next would address https://github.com/phetsims/chipper/issues/132.  Looks like @samreid is the lucky winner.

**Comment by ariel-phet** [comment]
@samreid back to you

**Comment by pixelzoom** [comment]
Note that  phetsims/chipper#132 was assigned to me because I started working on models-of-the-hydrogen-atom, and strings will need to be migrated for that.  But since bending-light has just been published, it seems like migrating the strings has some urgency to it - and probably should have been done before publishing.  At this point, you'll also need to be careful not to overwrite any translations that are done before you migrate the strings.

**Comment by samreid** [comment]
I've created issue #341 for me to migrate the Java strings to babel.  Reassigning this issue to @ariel-phet  since there are other items remaining in the checklist above.

**Comment by ariel-phet** [comment]
Assigning to @arouinfar to check off interview items
